# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MovieChecker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieChecker
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn'

  target 'MovieCheckerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieCheckerUITests' do
    # Pods for testing
  end

end
